---
deployments:
  eucedev1:
    version: "v0.0.1"
    account: "000344419000"
    region: "eu-central"
  eucestg1:
    version: "v0.0.2"
    account: "111855519000"
    region: "eu-central"
  useaprd1:
    version: "v0.0.3"
    account: "222166644000"
    region: "us-east"

terraform: "v0.0.1"
